/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'fragrance' : IDL.Null,
  'skincare' : IDL.Null,
  'makeup' : IDL.Null,
  'bodycare' : IDL.Null,
  'haircare' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'filterByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsSortedByPrice' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProductInWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'fragrance' : IDL.Null,
    'skincare' : IDL.Null,
    'makeup' : IDL.Null,
    'bodycare' : IDL.Null,
    'haircare' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'filterByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsSortedByPrice' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProductInWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };